/follower:
  controller_manager:
    ros__parameters:
      update_rate: 50  # Hz

      arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      gripper_controller:
        type: position_controllers/GripperActionController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  arm_controller:

    ros__parameters:
      update_rate: 25
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - shoulder_pan
        - shoulder_lift
        - elbow_flex
        - wrist_flex
        - wrist_roll
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity

      gains:
        shoulder_pan:  {p: 0.0, i: 0.0, d: 0.0}
        shoulder_lift: {p: 0.0, i: 0.0, d: 0.0}
        elbow_flex:    {p: 0.0, i: 0.0, d: 0.0}
        wrist_flex:    {p: 0.0, i: 0.0, d: 0.0}
        wrist_roll:    {p: 0.0, i: 0.0, d: 0.0}

      state_publish_rate: 50.0
      action_monitor_rate: 20.0

      time_scaling: 1.1

  gripper_controller:
    ros__parameters:
      type: position_controllers/GripperActionController
      joint: gripper

#/leader:
#  controller_manager:
#    ros__parameters:
#      update_rate: 50  # Hz

#      joint_state_broadcaster:
#        type: joint_state_broadcaster/JointStateBroadcaster

#  joint_state_broadcaster:
#    ros__parameters:
#      type: joint_state_broadcaster/JointStateBroadcaster
#      joints:
#        - shoulder_pan
#        - shoulder_lift
#        - elbow_flex
#        - wrist_flex
#        - wrist_roll
#        - gripper

#     interfaces:
#        - position

/leader:
  controller_manager:
    ros__parameters:
      update_rate: 50

      # All controller have to be declared here:
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      
      arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      gripper_controller:
        type: position_controllers/GripperActionController

  # Params for specific controllers
  arm_controller:
    ros__parameters:
      joints:
        - shoulder_pan
        - shoulder_lift
        - elbow_flex
        - wrist_flex
        - wrist_roll
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity

  # Gripper gets controlled seperately 
  gripper_controller:
    ros__parameters:
      joint: gripper
